# Generated by Django 6.0.3 on 2026-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0003_alter_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
